### ISSUE TITLE
Works or does not work?

### ISSUE THREAD

**Issue by gerroon** [Thor77/Blueproximity#68]
Hi

I am trying to enable and disable Mpd outputs using this app. Only function that seems to trigger anything is the promixty command. I cant get it to anything with the lock and unlock commands :( 

Maybe I am not getting it. Maybe my values are wrong? I cant tell what unit they are also.

![selection_031](https://user-images.githubusercontent.com/8519469/41935057-13933c84-794e-11e8-8d98-16f745123f51.png)

**Comment by Thor77** [comment]
Hello there,
i'm very sorry to say that, but the current state of the code in this repository is not really usable, yet.
The backend is implemented nearly completely but the GUI is far from finished (work is taking place on the [gui-branch](https://github.com/Thor77/Blueproximity/tree/gui) for that).

Regarding your issue: Try running Blueproximity from a shell and look for log messages, if there's something wrong it should tell you. There are debug messages for (un)lock commands as well so you should be able to locate your problem more precisely.

**Comment by gerroon** [comment]
@Thor77 

Thanks for the reply, I will try the command line part.
